### PR TITLE
Add a few more screenshots for v6 web interface

### PR DESCRIPTION
**Pull request by rdwebdesign**
### What does this PR aim to accomplish?

Add the following images:
- System Settings (basic and expert);
- All settings (video - animated GIF);
- Tail Pi-hole Log (small video - animated GIF);
- Search Lists;

### Link documentation PRs if any are needed to support this PR:
none

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by rdwebdesign** [comment]
Note:

The image for _All Settings_ is a video (animated GIF) and its size is 2 MB.
I was able to convert the GIF to a MP4 (1.5 MB).

Both files are relatively big compared to other images here, but still small for a video.

If you think this is too big, I can create a different GIF file, or use an static GIF or PNG.

**Comment by yubiuser** [comment]
Do we need a video to show how to click on different setting categories?

**Comment by rdwebdesign** [comment]
We don't "need" a video (or images, if you want to be really strict), but images could make the README more attractive and easy to understand.

I think this video is better than simply showing a "slideshow" with static images of each screen, but we can remove it if there is an issue with its size.

**Review by yubiuser — APPROVED** [review]

**Comment by rdwebdesign** [comment]
Someone else will need to merge this PR because I don't have enough permissions in the repo.

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
