### PR TITLE
Add PADD screenshots of different sizes

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Adds screenshots of different sized PADD screens. Files can be used to fix the wiki and https://github.com/pi-hole/PADD/issues/286

### CODE REVIEW

**Comment by yubiuser** [comment]
As we have the `*.gif` now I don't think we'll need the individual images?

**Comment by rdwebdesign** [comment]
> As we have the *.gif now I don't think we'll need the individual images?

Unless you want to keep the images to reference them if you need to write a page or detail for a specific size.

**Comment by yubiuser** [comment]
I don't think I want to 
> write a page or detail for a specific size.

If one day, we can make new images with the then up-to-date interface.

**Review by rdwebdesign — APPROVED** [review]

**Comment by yubiuser** [comment]
@dschaper 

Please review and merge, I can't.

**Pull request merged**
