### PR TITLE
Add PADD screenshot

### PR DESCRIPTION
**Pull request by rdwebdesign**
## Thank you for your contribution to the Pi-hole Community! 

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**
 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions

---
- **What does this PR aim to accomplish?:**

Add the PADD screenshot.
 
- **How does this PR accomplish the above?:**

Adding the new file

- **What documentation changes (if any) are needed to support this PR?:**

none

---

**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by dschaper** [comment]
Can you run it through a lossless compressor?

**Comment by rdwebdesign** [comment]
~~I think this is already compressed.~~ I used a different compressor and now the file is smaller.

**Comment by yubiuser** [comment]
Where did you grab that screenshot? It shows really, really outdated versions....

**Comment by yubiuser** [comment]
PR to include the screenshot: https://github.com/pi-hole/PADD/pull/231

**Review by yubiuser — DISMISSED** [review]

**Comment by dschaper** [comment]
I left a compressed version on Team that can be used here.

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
