### PR TITLE
Add new assets for readme

### PR DESCRIPTION
**Pull request by WaLLy3K**
As above. Once merged, I'll be updating https://github.com/pi-hole/pi-hole/pull/1717 with my latest draft with updated links.

### CODE REVIEW

**Comment by dschaper** [comment]
We already have a PayPal black png, do we need another svg of the same image? (And the viewboxes on the SVG's have a lot of extra whitespace, they could be trimmed up to just the logo.)

**Comment by WaLLy3K** [comment]
The PayPal and Bitcoin images are PNG's which don't look good on retina displays (iPhones, Macbooks, etc). The whitespace is intentional, as they're being used to indent the text like bullet points.

**Comment by dschaper** [comment]
Okay, that sounds good. I would like if we could close up the view window so that the `svg` could be used in other places now that all common browsers support `svg` without issue, but if there's not an easy way to place the file in markdown in a way that supports your intended layout, I guess we will have to go with what you have submitted. One change that I would like to see first though is in the file naming so they match what we have existing. 

    bitcoin-badge-black.svg
    paypal-badge-black.svg
    blacklist-cli.gif

**Comment by WaLLy3K** [comment]
The vectors are 48x48px, meant to be displayed at 24x24px; so I've centered the images rather than cut out the white space. Hopefully that works! :smile:

**Comment by jacobsalmela** [comment]
Looks like the PayPal one didn't get renamed

**Review by jacobsalmela — APPROVED** [review]

**Pull request merged**
